### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by CHRINIMUE** [kort/kort#111]
When I open the Website play.kort.ch I cant login. I need to login in the "Protected Area" with a username and password. But I don't know them. (obviously) :-( 
![bildschirmfoto vom 2016-08-19 19 26 50](https://cloud.githubusercontent.com/assets/15434539/17818240/f3890b14-6642-11e6-9f88-1a21e6dfacea.png)

**Comment by dominicmh** [comment]
Due to the development of Kort as a smartphone app (https://github.com/kort/kort-reloaded) the web app (play.kort.ch) isn't available anymore – and won't be in the near future. If you have an Android smartphone you can start using the beta app today, otherwise some patience will be required.
